# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rtre.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rtre.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrtre.proto\"\x1d\n\x0bRiskRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\".\n\x0cRiskResponse\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0b\n\x03obi\x18\x02 \x01(\x01\x32:\n\x0bRiskService\x12+\n\nStreamRisk\x12\x0c.RiskRequest\x1a\r.RiskResponse0\x01\x42\x1cZ\x1agithub.com/janscheres/rtreb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rtre_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032github.com/janscheres/rtre'
  _globals['_RISKREQUEST']._serialized_start=14
  _globals['_RISKREQUEST']._serialized_end=43
  _globals['_RISKRESPONSE']._serialized_start=45
  _globals['_RISKRESPONSE']._serialized_end=91
  _globals['_RISKSERVICE']._serialized_start=93
  _globals['_RISKSERVICE']._serialized_end=151
# @@protoc_insertion_point(module_scope)
