// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: rtre.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskRequest) Reset() {
	*x = RiskRequest{}
	mi := &file_rtre_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskRequest) ProtoMessage() {}

func (x *RiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rtre_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskRequest.ProtoReflect.Descriptor instead.
func (*RiskRequest) Descriptor() ([]byte, []int) {
	return file_rtre_proto_rawDescGZIP(), []int{0}
}

func (x *RiskRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type RiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Obi           float64                `protobuf:"fixed64,2,opt,name=obi,proto3" json:"obi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskResponse) Reset() {
	*x = RiskResponse{}
	mi := &file_rtre_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskResponse) ProtoMessage() {}

func (x *RiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rtre_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskResponse.ProtoReflect.Descriptor instead.
func (*RiskResponse) Descriptor() ([]byte, []int) {
	return file_rtre_proto_rawDescGZIP(), []int{1}
}

func (x *RiskResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *RiskResponse) GetObi() float64 {
	if x != nil {
		return x.Obi
	}
	return 0
}

var File_rtre_proto protoreflect.FileDescriptor

const file_rtre_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"rtre.proto\"%\n" +
	"\vRiskRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\">\n" +
	"\fRiskResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03obi\x18\x02 \x01(\x01R\x03obi2:\n" +
	"\vRiskService\x12+\n" +
	"\n" +
	"StreamRisk\x12\f.RiskRequest\x1a\r.RiskResponse0\x01B\x1fZ\x1dgithub.com/janscheres/rtre/pbb\x06proto3"

var (
	file_rtre_proto_rawDescOnce sync.Once
	file_rtre_proto_rawDescData []byte
)

func file_rtre_proto_rawDescGZIP() []byte {
	file_rtre_proto_rawDescOnce.Do(func() {
		file_rtre_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rtre_proto_rawDesc), len(file_rtre_proto_rawDesc)))
	})
	return file_rtre_proto_rawDescData
}

var file_rtre_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rtre_proto_goTypes = []any{
	(*RiskRequest)(nil),  // 0: RiskRequest
	(*RiskResponse)(nil), // 1: RiskResponse
}
var file_rtre_proto_depIdxs = []int32{
	0, // 0: RiskService.StreamRisk:input_type -> RiskRequest
	1, // 1: RiskService.StreamRisk:output_type -> RiskResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rtre_proto_init() }
func file_rtre_proto_init() {
	if File_rtre_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rtre_proto_rawDesc), len(file_rtre_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rtre_proto_goTypes,
		DependencyIndexes: file_rtre_proto_depIdxs,
		MessageInfos:      file_rtre_proto_msgTypes,
	}.Build()
	File_rtre_proto = out.File
	file_rtre_proto_goTypes = nil
	file_rtre_proto_depIdxs = nil
}
